### PR TITLE
feature: turn on FFI API for stream module

### PR DESCRIPTION
**Pull request by james-callahan**
Originally part of https://github.com/openresty/stream-lua-nginx-module/pull/122

This PR removes the limitations that force us to use `NGX_LUA_NO_FFI_API` in the stream module.

### CODE REVIEW

**Comment by agentzh** [comment]
@dndx Will you have a look at this?

We're going to remove the non-FFI APIs in both the stream and http lua modules anyway.

**Comment by dndx** [comment]
@james-callahan Have you ran stream_lua's tests with this change?

**Comment by james-callahan** [comment]
> @james-callahan Have you ran stream_lua's tests with this change?

No. I was never able to get the test suite to run on my computer.

**Comment by agentzh** [comment]
@james-callahan Then it may break stuff. See how travis ci runs the test suite, for example:

https://github.com/openresty/stream-lua-nginx-module/blob/master/.travis.yml

Or you can just use travis ci to test your own branch.

**Pull request closed without merging**
